baseURL = "https://uapi-group.org/kernel-features"
languageCode = "en-us"
title = "UAPI Group Kernel Feature Wishlist"
theme = "hugo-book"

[taxonomies]
  category = "categories"

[[menu.before]]
  name = "Back to top"
  url = "/.."
  weight = 1

[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group/kernel-features"
  weight = 11

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookPortableLinks = true
  BookRepo = 'https://github.com/uapi-group/kernel-features'
  BookCommitPath = 'commit'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/website/{{ .Path }}'
  BookSection = '/'
  BookTheme = 'auto'
  BookSearch = true
  BookDateFormat = "January 2, 2006"
